sudo: false
dist: trusty
language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura coveralls:report